plugins {
    id 'net.minecraftforge.gradle' version '[6.0.24,)'
    id 'org.spongepowered.mixin' version '0.7.38'
}

base {
    archivesName = "librarian-filter-forge-${project.minecraft_version}"
}

mixin {
    add sourceSets.main, "librarian-filter.refmap.json"
    config "librarian-filter.mixins.json"
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', 'librarian_filter'

            mods {
                "librarian_filter" {
                    source sourceSets.main
                    source project(":common").sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'librarian_filter'

            mods {
                "librarian_filter" {
                    source sourceSets.main
                    source project(":common").sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
    
    compileOnly project(":common")
}

tasks.withType(Jar).configureEach {
    from project(":common").sourceSets.main.output
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}
