plugins {
    id 'dev.architectury.loom' version '1.9-SNAPSHOT'
}

base {
    archivesName = "librarian-filter-forge-${project.minecraft_version}"
}

loom {
    forge {
        mixinConfig "librarian-filter.mixins.json"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

    compileOnly project(":common")
}

tasks.withType(Jar).configureEach {
    from project(":common").sourceSets.main.output
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}
